[user]

[user.UserId]
type = "string"
primaryKey = true

[user.Config]
type = "string"
default = """
-- .terriblerc

edit '--// Blank notepad \\\\--'

editor:addCommand('rep', function(args)
    local repeated = ''

    local toRepeat = args[1]
    local count = tonumber(args[2])

    if not count then
      return editor:reject('Invalid count')
    end

    for i = 1, count do
      repeated = repeated .. toRepeat
    end

    editor:editCurrentLine(repeated)
end)
"""

[user.Xp]
type = "number"
default = 0